name: Commitlint pull request title check
run-name: ${{ github.actor }} is running commitlint check on pull request title.
on:
    pull_request:
        types: [opened, reopened, edited, synchronize]
        branches: ['*']

permissions: read-all
jobs:
    pullRequestTitleCheck:
        name: Running commitlint check on pull request title
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v4.2.2

            - name: Setup node
              uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # tag=v4.2.0
              with:
                  node-version: 22

            - name: Run commitlint check for pull request title
              run: |
                  npm ci
                  echo "${{ github.event.pull_request.title }}" | npx commitlint --verbose
