name: ESLint
run-name: ${{ github.actor }} is running ESLint check on code
on:
    push:
        branches: ['*']
    pull_request:
        types: [opened, reopened]
        branches: ['*']

permissions: read-all
jobs:
    eslint:
        name: Running ESLint check on code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # tag=v4.1.0

            - name: Setup node
              uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # tag=3.8.1
              with:
                  node-version: 18

            - name: Run ESLint
              run: |
                  npm ci
                  npm run eslint-ci
