name: ESLint
run-name: ${{ github.actor }} is running ESLint check on code
on:
    push:
        branches: ['*']
    pull_request:
        types: [opened, reopened, edited, synchronize]
        branches: ['*']

permissions: read-all
jobs:
    eslint:
        name: Running ESLint check on code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v4.2.2

            - name: Setup node
              uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # tag=v4.2.0
              with:
                  node-version: 22

            - name: Run ESLint
              run: |
                  npm ci
                  npm run eslint-ci
